import { StitchHeader } from "@/components/stitch/StitchHeader";
import { StitchFooter } from "@/components/stitch/StitchFooter";
import { StitchServicePanel } from "@/components/stitch/StitchServicePanel";
import type { IndustryCase, StitchService } from "@/types/stitch";

const industries: IndustryCase[] = [
  { title: "Seri İmalat & Otomotiv Yan Sanayi", description: "Yüksek çevrim hızlı robotik punta, kaynak ve pres besleme hatları. Parça bazlı barkod/RFID takibi ile sıfır hatalı montaj.", result: "DURUŞ -%42" },
  { title: "Ağır Makine & Ekipman Üretimi", description: "Portal frezeler ve hidrolik test stantlarında mekanik yük sensörleri ve titreşim analitiği.", result: "HIZ +%65" },
  { title: "Dağıtım, Depo & Lojistik Merkezleri", description: "Otomatik konveyör ayrıştırma, AS/RS dikey depolama ve ERP ile milisaniyelik paket yönlendirme.", result: "VERİ %99.99" },
  { title: "Enerji & Şebeke Dağıtım Tesisleri", description: "IEC 61850 standartlarında SCADA izleme, harmonik filtreleme ve uzaktan kesici kontrolü.", result: "TEPKİ -%55" },
  { title: "Saha Servis & Teknik Operasyonlar", description: "Çevrimdışı çalışabilen mobil saha yönetimi, dijital iş emri ve otomatik yedek parça entegrasyonu.", result: "FİRE -%24" },
  { title: "Endüstriyel Hammadde & Toptan", description: "Silo tartım ve dozajlama verilerinin ticari yazılıma doğrudan aktarımı.", result: "OEE +%34" },
];


function RequestForm() {
  return <section className="stitch-request" id="proje-talep"><div><p className="stitch-kicker">MÜHENDİSLİK TALEBİ // ŞARTNAME İNCELEME</p><h2>Neye ihtiyacınız olduğunu bize iletin.</h2><p>Tesisinizin mevcut durumunu, karşılaştığınız darboğazları veya hedeflediğiniz otomasyon/yazılım kapsamını paylaşın.</p><aside>✓ MÜHENDİS DANIŞMANLIK GARANTİSİ<br/><span>Talebiniz en geç 24 saat içinde kıdemli proje mühendisi tarafından incelenir.</span></aside></div><form onSubmit={event => event.preventDefault()}><fieldset><legend>1. PROJE KAPSAMINI SEÇİN</legend><div className="scope"><button type="button">Donanım &amp; Otomasyon</button><button type="button">Yazılım &amp; Dijital</button><button type="button">Entegre Hibrit Proje</button></div></fieldset><label>Ad Soyad *<input required /></label><label>Şirket Ünvanı *<input required /></label><label>İletişim E-Postası *<input type="email" required /></label><label>Faaliyet Sektörü *<select defaultValue=""><option value="" disabled>Seçiniz</option><option>Seri İmalat & Otomotiv Yan Sanayi</option><option>Dağıtım, Depo & Lojistik</option><option>Diğer Endüstriyel Tesis</option></select></label><label className="full">Operasyonel Zorluğunuz / Proje Detayı *<textarea rows={4} required /></label><button className="submit" type="submit">ŞARTNAMEYİ İNCELEMEYE GÖNDER →</button><small>▣ Bilgileriniz NDA ve KVKK kapsamında korunur</small></form></section>;
}

export default function StitchLanding() {
  return <main className="stitch-page"><StitchHeader/><section className="stitch-intro"><p className="stitch-kicker">STRATEJİK SEÇİM // ENDÜSTRİYEL MİMARİ <b>SYS-DECISION ENGINE V4.2</b></p><h1>İşletmeniz için hangisine ihtiyacınız var?</h1><p>Fiziksel üretim sahanızı veya dijital karar alma mekanizmanızı dönüştürmek için yönünüzü seçin.</p><div className="stitch-split"><StitchServicePanel service="hardware"/><StitchServicePanel service="software"/></div></section><section className="stitch-bridge" id="yol-haritasi"><p className="stitch-kicker">END-TO-END SİNERJİ MODELİ</p><h2>Tek Ortak, İki Güçlü Yetkinlik</h2><p>Atölye zeminindeki çelikten buluttaki algoritmaya uzanan köprüyü tek mühendislik ekibiyle kurarız.</p><div className="stitch-layers"><article><p className="stitch-kicker">KATMAN 01 // FİZİKSEL MEKANİK</p><h3>Fiziksel Gerçeklik</h3><p>Ağır sanayi hatları, servo motorlar, hidrolik-pnömatik aktüatörler, şalt panoları ve sertifikalı PLC mimarileri.</p></article><article><p className="stitch-kicker">KATMAN 02 // DİJİTAL İSTİHBARAT</p><h3>Dijital İstihbarat</h3><p>Bulut ve edge telemetri, kestirimci bakım yapay zekası, kurumsal ERP modülleri ve C-level analitik paneller.</p></article></div></section><section className="stitch-industries" id="sektorler"><p className="stitch-kicker">SEKTÖREL ÇÖZÜM MATRİSİ</p><h2>Endüstriyel Zorluklara Özel Mimari</h2><div>{industries.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.description}</p><b>{item.result}</b></article>)}</div></section><section className="stitch-metrics"><div><strong>+%34</strong><span>ORTALAMA OEE ARTIŞI</span></div><div><strong>420+</strong><span>DEVREYE ALINAN PANO &amp; HAT</span></div><div><strong>&lt; 1.2 sn</strong><span>TELEMETRİ SENKRONİZASYONU</span></div><div><strong>18+ yıl</strong><span>SAHA &amp; YAZILIM TECRÜBESİ</span></div></section><section className="stitch-cases" id="vakalar"><p className="stitch-kicker">DOĞRULANMIŞ SAHA ÇIKTILARI</p><h2>Gerçekleşen Proje Raporları</h2><div><article><p>RAPOR ID // TR-ENG-2024 · KOCAELİ</p><h3>Robotik Şasi Kaynak Hattı Modernizasyonu &amp; ERP İntikal Sistemi</h3><p>Altı robot hücresi revize edilerek emniyet PLC’leri ile donatıldı; kaynak parametreleri anlık SAP üretim modülüne işlendi.</p><b>ÇIKTI: Vardiya Başına +140 Şasi Üretimi</b></article><article><p>İZMİR // LOJİSTİK &amp; SOĞUK ZİNCİR</p><h3>Dağıtık Depo Isı Telemetrisi &amp; Otonom Sorter Entegrasyonu</h3><p>180 kablosuz sensör ve 2 km konveyör sorter kontrol panosu, özel bulut yazılımıyla tek ağda birleştirildi.</p><b>ÇIKTI: %100 Soğuk Zincir İzlenebilirliği</b></article></div></section><RequestForm/><StitchFooter/></main>;
}
